# Generated by Django 2.2.4 on 2019-08-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='projeto',
            field=models.CharField(choices=[('Poligonos', 'Poligonos'), ('Triangulos', 'Triangulos'), ('Quadrilateros', 'Quadrilateros')], max_length=50),
        ),
    ]
