# Generated by Django 2.2.4 on 2019-09-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=120)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=2)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Evento')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.IntegerField(choices=[(1, 'Matemática'), (2, 'Ciências')])),
                ('descricao', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')])),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Evento')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Participante')),
            ],
            options={
                'verbose_name': 'Participante Projeto',
                'verbose_name_plural': 'Participantes Projetos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Projeto'),
        ),
    ]
