# Generated by Django 2.2.4 on 2019-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.IntegerField(choices=[('1', 'Matemática'), ('2', 'Ciências')])),
                ('descricao', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
