# Generated by Django 2.2.4 on 2019-09-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.CharField(choices=[('1', 'Grupo - 1 - CIENCIAS'), ('2', 'Grupo - 2 - CIENCIAS'), ('3', 'Grupo - 3 - CIENCIAS'), ('4', 'Grupo - 4 - CIENCIAS'), ('5', 'Grupo - 1 - MATEMATICA'), ('6', 'Grupo - 2 - MATEMATICA'), ('7', 'Grupo - 3 - MATEMATICA')], max_length=1),
        ),
    ]
