# Generated by Django 2.2.4 on 2019-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='quantidade',
            field=models.IntegerField(choices=[('3', '3'), ('4', '4')]),
        ),
    ]
