# Generated by Django 2.2.4 on 2019-09-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20190903_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.CharField(choices=[('1', 'GRUPO - 1 - CIENCIAS'), ('2', 'GRUPO - 2 - CIENCIAS'), ('3', 'GRUPO - 3 - CIENCIAS'), ('4', 'GRUPO - 4 - CIENCIAS'), ('5', 'GRUPO - 1 - MATEMATICA'), ('6', 'GRUPO - 2 - MATEMATICA'), ('7', 'GRUPO - 3 - MATEMATICA')], max_length=2),
        ),
    ]
