# Generated by Django 2.2.4 on 2019-09-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20190903_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Evento'),
        ),
    ]
