# Generated by Django 2.2.4 on 2019-09-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_evento_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participante',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='materia',
            field=models.IntegerField(choices=[(1, 'Matemática'), (2, 'Ciências')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='quantidade',
            field=models.IntegerField(choices=[(3, '3'), (4, '4')]),
        ),
        migrations.CreateModel(
            name='ParticipanteProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Evento')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Participante')),
            ],
            options={
                'verbose_name': 'Participante Projeto',
                'verbose_name_plural': 'Participantes Projetos',
            },
        ),
    ]
