# Generated by Django 2.2.5 on 2019-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20190902_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteprojeto',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
