# Generated by Django 2.2.5 on 2019-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_participanteprojeto_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='quantidade',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
