# Generated by Django 2.2.4 on 2019-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='projeto',
            field=models.CharField(choices=[('Labirinto dos 5 sentidos', 'Labirinto dos 5 sentidos'), ('Daltonismo', 'Daltonismo'), ('Cinema na caixa', 'Cinema na caixa'), ('Sistema Digestório', 'Sistema Digestório')], max_length=50),
        ),
    ]
