# Generated by Django 2.2.4 on 2019-08-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciencias', '0002_auto_20190830_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participante',
            new_name='CienciasParticipante',
        ),
        migrations.RenameModel(
            old_name='Projeto',
            new_name='CienciasProjeto',
        ),
    ]
